-- MySQL Script generated by MySQL Workbench
-- Sat Sep 10 10:58:10 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rdb_for_all
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rdb_for_all
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rdb_for_all` DEFAULT CHARACTER SET utf8 ;
USE `rdb_for_all` ;

-- -----------------------------------------------------
-- Table `rdb_for_all`.`instrument`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdb_for_all`.`instrument` (
  `id` INT NOT NULL,
  `short_name` VARCHAR(10) NOT NULL,
  `test_doc` LONGBLOB NULL,
  `collection_manual` LONGBLOB NULL,
  `analysis_procedure_manual` LONGBLOB NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdb_for_all`.`booklet_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdb_for_all`.`booklet_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `instrument_id` INT NOT NULL,
  `short_name` VARCHAR(10) NULL,
  `description` VARCHAR(1000) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_item_orders_instrument1_idx` (`instrument_id` ASC) VISIBLE,
  CONSTRAINT `fk_item_orders_instrument1`
    FOREIGN KEY (`instrument_id`)
    REFERENCES `rdb_for_all`.`instrument` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdb_for_all`.`study`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdb_for_all`.`study` (
  `id` INT NOT NULL,
  `studyname` VARCHAR(45) NOT NULL,
  `date_start` DATE NULL,
  `date_end` DATE NULL,
  `date_delete_before` DATE NULL,
  `documentation` BLOB NOT NULL,
  `responsible_person` VARCHAR(45) NOT NULL,
  `comment` VARCHAR(1000) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdb_for_all`.`group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdb_for_all`.`group` (
  `id` INT NOT NULL,
  `description` VARCHAR(1000) NULL,
  `shortform` VARCHAR(10) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdb_for_all`.`unit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdb_for_all`.`unit` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date_start` DATETIME NOT NULL,
  `date_end` DATETIME NOT NULL,
  `timepoint` INT NOT NULL,
  `protocol` LONGBLOB NULL,
  `study_id` INT NOT NULL,
  `group_id` INT NOT NULL,
  `comment` VARCHAR(1000) NULL,
  INDEX `fk_units_study1_idx` (`study_id` ASC) VISIBLE,
  INDEX `fk_units_group1_idx` (`group_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_units_study1`
    FOREIGN KEY (`study_id`)
    REFERENCES `rdb_for_all`.`study` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_units_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `rdb_for_all`.`group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdb_for_all`.`booklet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdb_for_all`.`booklet` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `int_ident` VARCHAR(45) NOT NULL,
  `scan` LONGBLOB NULL,
  `booklet_type_id` INT NOT NULL,
  `unit_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_booklet_booklet_type1_idx` (`booklet_type_id` ASC) VISIBLE,
  INDEX `fk_booklet_unit1_idx` (`unit_id` ASC) VISIBLE,
  CONSTRAINT `fk_booklet_booklet_type1`
    FOREIGN KEY (`booklet_type_id`)
    REFERENCES `rdb_for_all`.`booklet_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_booklet_unit1`
    FOREIGN KEY (`unit_id`)
    REFERENCES `rdb_for_all`.`unit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'This is the dataset for the booklet';


-- -----------------------------------------------------
-- Table `rdb_for_all`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdb_for_all`.`item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `short_name` VARCHAR(10) NOT NULL,
  `scan` LONGBLOB NULL,
  `correct` VARCHAR(45) NULL,
  `format` VARCHAR(45) NOT NULL,
  `item_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_item_item1_idx` (`item_id` ASC) VISIBLE,
  CONSTRAINT `fk_item_item1`
    FOREIGN KEY (`item_id`)
    REFERENCES `rdb_for_all`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rdb_for_all`.`response`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdb_for_all`.`response` (
  `id` INT NOT NULL,
  `item_id` INT NOT NULL,
  `booklet_id` INT NOT NULL,
  `order_responded` INT NULL,
  `resp_blob` LONGBLOB NULL,
  `resp_int` INT NULL,
  `resp_char` VARCHAR(45) NULL,
  `resp_char_short` VARCHAR(10) NULL,
  `resp_textlong` VARCHAR(1000) NULL,
  INDEX `fk_responses_items_idx` (`item_id` ASC) VISIBLE,
  PRIMARY KEY (`id`, `item_id`, `booklet_id`),
  INDEX `fk_response_booklets1_idx` (`booklet_id` ASC) VISIBLE,
  CONSTRAINT `fk_responses_items`
    FOREIGN KEY (`item_id`)
    REFERENCES `rdb_for_all`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_response_booklets1`
    FOREIGN KEY (`booklet_id`)
    REFERENCES `rdb_for_all`.`booklet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdb_for_all`.`coder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdb_for_all`.`coder` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first name` VARCHAR(45) NOT NULL,
  `laste name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdb_for_all`.`resp_type_fixed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdb_for_all`.`resp_type_fixed` (
  `reponse` VARCHAR(10) NOT NULL,
  `comment` VARCHAR(1000) NULL,
  `meaning_fixed` VARCHAR(1000) NULL,
  PRIMARY KEY (`reponse`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdb_for_all`.`dimension`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdb_for_all`.`dimension` (
  `id` INT NOT NULL,
  `short_name` VARCHAR(10) NOT NULL,
  `description` VARCHAR(1000) NOT NULL,
  `comment` VARCHAR(1000) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdb_for_all`.`dimensionality`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdb_for_all`.`dimensionality` (
  `item_id` INT NOT NULL,
  `dimension_id` INT NOT NULL,
  PRIMARY KEY (`item_id`, `dimension_id`),
  INDEX `fk_dimensionality_item1_idx` (`item_id` ASC) VISIBLE,
  INDEX `fk_dimensionality_dimension1_idx` (`dimension_id` ASC) VISIBLE,
  CONSTRAINT `fk_dimensionality_item1`
    FOREIGN KEY (`item_id`)
    REFERENCES `rdb_for_all`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dimensionality_dimension1`
    FOREIGN KEY (`dimension_id`)
    REFERENCES `rdb_for_all`.`dimension` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdb_for_all`.`group_relation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdb_for_all`.`group_relation` (
  `group_id1` INT NOT NULL AUTO_INCREMENT,
  `group_id2` INT NOT NULL,
  `relation_description` VARCHAR(1000) NOT NULL,
  INDEX `fk_group_has_group_group2_idx` (`group_id2` ASC) VISIBLE,
  INDEX `fk_group_has_group_group1_idx` (`group_id1` ASC) VISIBLE,
  PRIMARY KEY (`group_id1`, `group_id2`),
  CONSTRAINT `fk_group_has_group_group1`
    FOREIGN KEY (`group_id1`)
    REFERENCES `rdb_for_all`.`group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_group_has_group_group2`
    FOREIGN KEY (`group_id2`)
    REFERENCES `rdb_for_all`.`group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdb_for_all`.`scheme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdb_for_all`.`scheme` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `manual` BLOB NOT NULL,
  `description` VARCHAR(1000) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdb_for_all`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdb_for_all`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `short_form` VARCHAR(10) NOT NULL,
  `description` VARCHAR(1000) NOT NULL,
  `scheme_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_categories_scheme1_idx` (`scheme_id` ASC) VISIBLE,
  CONSTRAINT `fk_categories_scheme1`
    FOREIGN KEY (`scheme_id`)
    REFERENCES `rdb_for_all`.`scheme` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdb_for_all`.`round`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdb_for_all`.`round` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `begin` DATETIME NULL,
  `end` DATETIME NULL,
  `goal` VARCHAR(1000) NULL,
  `round_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_round_round1_idx` (`round_id` ASC) VISIBLE,
  CONSTRAINT `fk_round_round1`
    FOREIGN KEY (`round_id`)
    REFERENCES `rdb_for_all`.`round` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdb_for_all`.`assignment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdb_for_all`.`assignment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cont_value` DECIMAL(100,50) NULL,
  `begin` DECIMAL(10,5) NULL,
  `end` DECIMAL(10,5) NULL,
  `unit` VARCHAR(10) NULL,
  `coder_note` VARCHAR(1000) NULL,
  `comment` VARCHAR(1000) NULL,
  `all` BINARY(1) NULL,
  `category_id` INT NOT NULL,
  `round_id` INT NOT NULL,
  `response_id` INT NOT NULL,
  `response_item_id` INT NOT NULL,
  `response_booklet_id` INT NOT NULL,
  INDEX `fk_assignments_categories1_idx` (`category_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  INDEX `fk_assignments_round1_idx` (`round_id` ASC) VISIBLE,
  INDEX `fk_assignment_response1_idx` (`response_id` ASC, `response_item_id` ASC, `response_booklet_id` ASC) VISIBLE,
  CONSTRAINT `fk_assignments_categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `rdb_for_all`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_assignments_round1`
    FOREIGN KEY (`round_id`)
    REFERENCES `rdb_for_all`.`round` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_assignment_response1`
    FOREIGN KEY (`response_id` , `response_item_id` , `response_booklet_id`)
    REFERENCES `rdb_for_all`.`response` (`id` , `item_id` , `booklet_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdb_for_all`.`item_position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdb_for_all`.`item_position` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `item_id` INT NOT NULL,
  `booklet_type_id` INT NOT NULL,
  `position` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_item_orders_items1_idx` (`item_id` ASC) VISIBLE,
  INDEX `fk_item_order_booklet_type1_idx` (`booklet_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_item_orders_items1`
    FOREIGN KEY (`item_id`)
    REFERENCES `rdb_for_all`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_order_booklet_type1`
    FOREIGN KEY (`booklet_type_id`)
    REFERENCES `rdb_for_all`.`booklet_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdb_for_all`.`coder_has_assignment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdb_for_all`.`coder_has_assignment` (
  `coder_id` INT NOT NULL,
  `assignment_id` INT NOT NULL,
  PRIMARY KEY (`coder_id`, `assignment_id`),
  INDEX `fk_coder_has_assignment_assignment1_idx` (`assignment_id` ASC) VISIBLE,
  INDEX `fk_coder_has_assignment_coder1_idx` (`coder_id` ASC) VISIBLE,
  CONSTRAINT `fk_coder_has_assignment_coder1`
    FOREIGN KEY (`coder_id`)
    REFERENCES `rdb_for_all`.`coder` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_coder_has_assignment_assignment1`
    FOREIGN KEY (`assignment_id`)
    REFERENCES `rdb_for_all`.`assignment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdb_for_all`.`item_has_resp_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdb_for_all`.`item_has_resp_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `item_id` INT NOT NULL,
  `resp_type__fixed` INT NULL,
  `meaning_individual` VARCHAR(1000) NOT NULL,
  `resp_type` VARCHAR(45) NULL,
  `key` INT NULL COMMENT 'If it is correct the correct solution',
  `key_prop` VARCHAR(45) NULL,
  INDEX `fk_item_has_resp_type_resp_type1_idx` (`resp_type__fixed` ASC) VISIBLE,
  INDEX `fk_item_has_resp_type_item1_idx` (`item_id` ASC) VISIBLE,
  PRIMARY KEY (`id`, `item_id`),
  CONSTRAINT `fk_item_has_resp_type_item1`
    FOREIGN KEY (`item_id`)
    REFERENCES `rdb_for_all`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_has_resp_type_resp_type1`
    FOREIGN KEY (`resp_type__fixed`)
    REFERENCES `rdb_for_all`.`resp_type_fixed` (`reponse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rdb_for_all`.`dimension_relation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdb_for_all`.`dimension_relation` (
  `dimension_id1` INT NOT NULL,
  `dimension_id2` INT NOT NULL,
  `relation` VARCHAR(1000) NULL,
  PRIMARY KEY (`dimension_id1`, `dimension_id2`),
  INDEX `fk_dimension_has_dimension_dimension2_idx` (`dimension_id2` ASC) VISIBLE,
  INDEX `fk_dimension_has_dimension_dimension1_idx` (`dimension_id1` ASC) VISIBLE,
  CONSTRAINT `fk_dimension_has_dimension_dimension1`
    FOREIGN KEY (`dimension_id1`)
    REFERENCES `rdb_for_all`.`dimension` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dimension_has_dimension_dimension2`
    FOREIGN KEY (`dimension_id2`)
    REFERENCES `rdb_for_all`.`dimension` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdb_for_all`.`stand_resp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdb_for_all`.`stand_resp` (
  `item_has_resp_type_id` INT NOT NULL,
  `item_has_resp_type_item_id` INT NOT NULL,
  `response_id` INT NOT NULL,
  `response_item_id` INT NOT NULL,
  `response_booklet_id` INT NOT NULL,
  PRIMARY KEY (`item_has_resp_type_id`, `item_has_resp_type_item_id`, `response_id`, `response_item_id`, `response_booklet_id`),
  INDEX `fk_stand_resp_response1_idx` (`response_id` ASC, `response_item_id` ASC, `response_booklet_id` ASC) VISIBLE,
  CONSTRAINT `fk_stand_resp_item_has_resp_type1`
    FOREIGN KEY (`item_has_resp_type_id` , `item_has_resp_type_item_id`)
    REFERENCES `rdb_for_all`.`item_has_resp_type` (`id` , `item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stand_resp_response1`
    FOREIGN KEY (`response_id` , `response_item_id` , `response_booklet_id`)
    REFERENCES `rdb_for_all`.`response` (`id` , `item_id` , `booklet_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
